CREATE TABLE user(
user_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
username VARCHAR(150) NOT NULL,
password VARCHAR(150) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
role_id INT NOT NULL,
FOREIGN KEY (role_id) REFERENCES role(role_id));


CREATE TABLE role(
role_id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
role_name VARCHAR(150) NOT NULL
);